use super::catalog::{Entry, Family, FileSpec};

#[allow(clippy::too_many_lines)]
pub(super) fn default_catalog() -> Vec<Entry> {
    vec![
        Entry {
            id: "parakeet-tdt-0.6b-v3-int8".into(),
            family: Family::Asr,
            engine: "parakeet".into(),
            display_name: "Parakeet TDT 0.6B v3 (25 EU langs)".into(),
            description: "NVIDIA Parakeet TDT v3, 25 European languages. ~671 MB. \
                          Native word timestamps; default desktop and Android ASR.".into(),
            languages: vec!["bg","hr","cs","da","nl","en","et","fi","fr","de","el","hu","it","lv","lt","mt","pl","pt","ro","sk","sl","es","sv","ru","uk"]
                .into_iter().map(String::from).collect(),
            size_bytes: 670_478_772,
            default_active: true,
            android_default: true,
            desktop_only: false,
            files: vec![
                FileSpec {
                    url: "https://huggingface.co/csukuangfj/sherpa-onnx-nemo-parakeet-tdt-0.6b-v3-int8/resolve/main/encoder.int8.onnx".into(),
                    rel_path: "sherpa-onnx-nemo-parakeet-tdt-0.6b-v3-int8/encoder.int8.onnx".into(),
                    size_bytes: 652_184_281,
                    sha256: "acfc2b4456377e15d04f0243af540b7fe7c992f8d898d751cf134c3a55fd2247".into(),
                },
                FileSpec {
                    url: "https://huggingface.co/csukuangfj/sherpa-onnx-nemo-parakeet-tdt-0.6b-v3-int8/resolve/main/decoder.int8.onnx".into(),
                    rel_path: "sherpa-onnx-nemo-parakeet-tdt-0.6b-v3-int8/decoder.int8.onnx".into(),
                    size_bytes: 11_845_275,
                    sha256: "179e50c43d1a9de79c8a24149a2f9bac6eb5981823f2a2ed88d655b24248db4e".into(),
                },
                FileSpec {
                    url: "https://huggingface.co/csukuangfj/sherpa-onnx-nemo-parakeet-tdt-0.6b-v3-int8/resolve/main/joiner.int8.onnx".into(),
                    rel_path: "sherpa-onnx-nemo-parakeet-tdt-0.6b-v3-int8/joiner.int8.onnx".into(),
                    size_bytes: 6_355_277,
                    sha256: "3164c13fc2821009440d20fcb5fdc78bff28b4db2f8d0f0b329101719c0948b3".into(),
                },
                FileSpec {
                    url: "https://huggingface.co/csukuangfj/sherpa-onnx-nemo-parakeet-tdt-0.6b-v3-int8/resolve/main/tokens.txt".into(),
                    rel_path: "sherpa-onnx-nemo-parakeet-tdt-0.6b-v3-int8/tokens.txt".into(),
                    size_bytes: 93_939,
                    sha256: "d58544679ea4bc6ac563d1f545eb7d474bd6cfa467f0a6e2c1dc1c7d37e3c35d".into(),
                },
            ],
        },
        Entry {
            id: "whisper-cpp-large-v3-turbo-q8".into(),
            family: Family::Asr,
            engine: "whisper-cpp".into(),
            display_name: "Whisper large-v3-turbo (whisper.cpp, Q8_0, multilingual)".into(),
            description: "OpenAI Whisper large-v3-turbo via whisper.cpp with native word \
                          timestamps. 99 languages. ~874 MB.".into(),
            languages: vec!["auto","en","de","fr","es","it","pt","nl","pl","ru","uk","zh","ja","ko","ar","tr","hi"]
                .into_iter().map(String::from).collect(),
            size_bytes: 874_000_000,
            default_active: false,
            android_default: false,
            desktop_only: false,
            files: vec![FileSpec {
                url: "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-large-v3-turbo-q8_0.bin".into(),
                rel_path: "whisper-cpp-large-v3-turbo-q8/ggml-large-v3-turbo-q8_0.bin".into(),
                size_bytes: 874_188_075,
                sha256: "317eb69c11673c9de1e1f0d459b253999804ec71ac4c23c17ecf5fbe24e259a1".into(),
            }],
        },
        Entry {
            id: "silero-lang95-onnx".into(),
            family: Family::LangId,
            engine: String::new(),
            display_name: "Silero Lang95 (language identification)".into(),
            description: "Silero LangID classifier covering 95 languages. ~16 MB ONNX. \
                          Used for fast spoken-language detection before ASR routing.".into(),
            languages: Vec::new(),
            size_bytes: 16_500_000,
            default_active: true,
            android_default: true,
            desktop_only: false,
            files: vec![FileSpec {
                url: "https://huggingface.co/deepghs/silero-lang95-onnx/resolve/main/lang_classifier_95.onnx".into(),
                rel_path: "silero-lang95-onnx/lang_classifier_95.onnx".into(),
                size_bytes: 16_972_591,
                sha256: "12a91f706ad6ca5a5eba4e84a96739d077e56f121ec71db86a752f62e218a227".into(),
            }],
        },
        Entry {
            id: "gigaam-v3-ru".into(),
            family: Family::Asr,
            engine: "nemo-ctc".into(),
            display_name: "GigaAM v3 (Russian)".into(),
            description: "Sber GigaAM v3 NeMo CTC, Russian-only. Fast and accurate. ~225 MB.".into(),
            languages: vec!["ru".into()],
            size_bytes: 224_721_672,
            default_active: false,
            android_default: false,
            desktop_only: false,
            files: vec![
                FileSpec {
                    url: "https://huggingface.co/csukuangfj/sherpa-onnx-nemo-ctc-giga-am-v3-russian-2025-12-16/resolve/main/model.int8.onnx".into(),
                    rel_path: "sherpa-onnx-nemo-ctc-giga-am-v3-russian-2025-12-16/model.int8.onnx".into(),
                    size_bytes: 224_721_476,
                    sha256: "f86ebfa0429ced91be6054fc344827e9c6c2572f3c318416cd974b06f66437ec".into(),
                },
                FileSpec {
                    url: "https://huggingface.co/csukuangfj/sherpa-onnx-nemo-ctc-giga-am-v3-russian-2025-12-16/resolve/main/tokens.txt".into(),
                    rel_path: "sherpa-onnx-nemo-ctc-giga-am-v3-russian-2025-12-16/tokens.txt".into(),
                    size_bytes: 196,
                    sha256: "17cc514451bcceac9c280068c71502f8448f99e9fb1456b8d0761651fd0392f2".into(),
                },
            ],
        },
        Entry {
            id: "qwen3-0.6b-q4km".into(),
            family: Family::Llm,
            engine: "llama-cli".into(),
            display_name: "Qwen3 0.6B (Q4_K_M, namer)".into(),
            description: "Compact GGUF used by the auto-rename feature.".into(),
            languages: Vec::new(),
            size_bytes: 396_705_472,
            default_active: true,
            android_default: true,
            desktop_only: false,
            files: vec![FileSpec {
                url: "https://huggingface.co/unsloth/Qwen3-0.6B-GGUF/resolve/main/Qwen3-0.6B-Q4_K_M.gguf".into(),
                rel_path: "qwen3-0.6b-q4km.gguf".into(),
                size_bytes: 396_705_472,
                sha256: "ac2d97712095a558e31573f62f466a3f9d93990898b0ec79d7c974c1780d524a".into(),
            }],
        },
        Entry {
            id: "qwen3-1.7b-q4km".into(),
            family: Family::Llm,
            engine: "llama-cli".into(),
            display_name: "Qwen3 1.7B (Q4_K_M, namer)".into(),
            description: "Larger, slightly higher-quality naming. Slower on phone.".into(),
            languages: Vec::new(),
            size_bytes: 1_107_409_472,
            default_active: false,
            android_default: false,
            desktop_only: false,
            files: vec![FileSpec {
                url: "https://huggingface.co/unsloth/Qwen3-1.7B-GGUF/resolve/main/Qwen3-1.7B-Q4_K_M.gguf".into(),
                rel_path: "qwen3-1.7b-q4km.gguf".into(),
                size_bytes: 1_107_409_472,
                sha256: "b139949c5bd74937ad8ed8c8cf3d9ffb1e99c866c823204dc42c0d91fa181897".into(),
            }],
        },
        Entry {
            id: "sortformer-v2-onnx-4spk".into(),
            family: Family::Diarizer,
            engine: "sortformer-onnx".into(),
            display_name: "NVIDIA Sortformer 4-speaker v2.1 (ONNX)".into(),
            description: "NeMo-grade diarization for ≤4 speakers. Pure ONNX (~492 MB), no Python runtime, GPU-accelerated when available.".into(),
            languages: Vec::new(),
            size_bytes: 492_242_946,
            default_active: true,
            android_default: true,
            desktop_only: false,
            files: vec![FileSpec {
                url: "https://huggingface.co/cgus/diar_streaming_sortformer_4spk-v2.1-onnx/resolve/main/diar_streaming_sortformer_4spk-v2.1.onnx".into(),
                rel_path: "sortformer-v2-onnx/model.onnx".into(),
                size_bytes: 492_242_946,
                sha256: "82b9c735e1cfc6b36b4ff8a994d9a0573e922d0e80a58a8553b2c58f7aff0c00".into(),
            }],
        },
        Entry {
            id: "sherpa-pyannote-titanet".into(),
            family: Family::Diarizer,
            engine: "sherpa".into(),
            display_name: "pyannote-3.0 segmentation + TitaNet-Large".into(),
            description: "Fallback for >4 speakers or no-GPU systems. Pure ONNX (~102 MB)."
                .into(),
            languages: Vec::new(),
            size_bytes: 107_398_406,
            default_active: false,
            android_default: false,
            desktop_only: false,
            files: vec![
                FileSpec {
                    url: "https://huggingface.co/csukuangfj/sherpa-onnx-pyannote-segmentation-3-0/resolve/main/model.onnx".into(),
                    rel_path: "sherpa-onnx-pyannote-segmentation-3-0/model.onnx".into(),
                    size_bytes: 5_992_913,
                    sha256: "220ad67ca923bef2fa91f2390c786097bf305bceb5e261d4af67b38e938e1079".into(),
                },
                FileSpec {
                    url: "https://github.com/k2-fsa/sherpa-onnx/releases/download/speaker-recongition-models/nemo_en_titanet_large.onnx".into(),
                    rel_path: "titanet_large.onnx".into(),
                    size_bytes: 101_405_493,
                    sha256: String::new(),
                },
            ],
        },
    ]
}
